CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_SMP=y
CONFIG_MP_MAX_NUM_CPUS=4
CONFIG_RV_BOOT_HART=4
CONFIG_RISCV_MACHINE_TIMER=y
CONFIG_SYS_CLOCK_TICKS_PER_SEC=100
CONFIG_XIP=n
CONFIG_MAIN_STACK_SIZE=1024
CONFIG_BT=n
